// Generated by ts-to-zod
import { z } from "zod";

export const dns_record_type_input_t_zods = z.union([z.literal("A"), z.literal("AAAA"), z.literal("CNAME"), z.literal("MX"), z.literal("NS"), z.literal("TXT"), z.literal("SRV"), z.literal("SOA"), z.literal("CAA"), z.literal("PTR")]);

export const dns_resolver_object_input_t_zods = z.object({
    resolver_id: z.string().min(1).max(100).optional(),
    resolver_host: z.string().min(1).max(255),
    resolver_port: z.number().min(1).max(65535)
});

export const dns_resolver_endpoint_string_input_t_zods = z.string();

export const dns_resolver_endpoint_input_t_zods = z.union([dns_resolver_object_input_t_zods, dns_resolver_endpoint_string_input_t_zods]);

export const dns_lookup_request_input_t_zods = z.object({
    resolvers: z.array(dns_resolver_endpoint_input_t_zods),
    targets: z.array(z.string()),
    record_types: z.array(dns_record_type_input_t_zods).optional(),
    timeout_ms: z.number().min(1).max(60000).optional(),
    max_retries: z.number().min(0).max(10).optional(),
    concurrency_limit: z.number().min(1).max(1000).optional()
});

export const reverse_dns_lookup_request_input_t_zods = z.object({
    resolvers: z.array(dns_resolver_endpoint_input_t_zods),
    targets: z.array(z.string()),
    timeout_ms: z.number().min(1).max(60000).optional(),
    max_retries: z.number().min(0).max(10).optional(),
    concurrency_limit: z.number().min(1).max(1000).optional()
});
